name: dartkahoot
description: Dart library to interact with Kahoot
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.0.0
  http: ^0.13.1
  math_expressions: ^2.1.0
  
dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  test: ^1.14.4
